server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: USERSERVICES
              uri: lb://USERSERVICES
              predicates:
                - Path=/user/**

            - id: HOTELSERVICE
              uri: lb://HOTELSERVICE
              predicates:
                - Path=/hotels/**, /staffs/**

            - id: RATINGSERVICE
              uri: lb://RATINGSERVICE
              predicates:
                - Path=/ratings/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka